name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Add VPS host to known_hosts
      run: |
        ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Clean VPS directory
      run: |
        ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} << 'EOF'
          # Remove todos os arquivos e diretórios no VPS_APP_DIR
          rm -rf ${{ secrets.VPS_APP_DIR }}/*
          
          # Encontra e remove de forma segura todos os arquivos que começam com um ponto
          find ${{ secrets.VPS_APP_DIR }} -type f -name ".*" -exec rm -f {} +
          find ${{ secrets.VPS_APP_DIR }} -type d -name ".*" -exec rm -rf {} +
        EOF

    - name: Copy files to VPS
      run: |
        rsync -avz --delete -e "ssh -p ${{ secrets.VPS_PORT }}" ./ ${{ secrets.VPS_HOST }}:${{ secrets.VPS_APP_DIR }}/
